### ISSUE TITLE
Release 0.5, Chapter 3, Section 2 - Model Issue

### ISSUE THREAD

**Issue by dimsumthinking** [editorscut/ec008-swift-kickstart-2#1]
This is a sample issue. Please include the release version, chapter, and section as it's easier to locate the problem and fix it.

A brief description with a possible fix is also appreciated!

Thank you,

Daniel

**Comment by nathany** [comment]
Have you considered using an issue template? 

https://help.github.com/en/articles/creating-issue-templates-for-your-repository

**Comment by dimsumthinking** [comment]
Thank you Nathan - I will look into that for my new book.

Also can you please email me - I’d like to offer you my next book

Daniel

**Comment by nathany** [comment]
Will do. Thanks
