### ISSUE TITLE
Wrong name for variable

### ISSUE THREAD

**Issue by ichbindaa** [editorscut/ec008-swift-kickstart-2#100]
Chapter 3: Section 10: Name shadowing

> The advantage of shadowing is that we don't have to come up with a name for the unwrapped version of `fileURL`. The disadvantage is that we have two variables named `image` with different types. 

I asume the correct name for the variable mus be: `fileURL` instead of image

**Comment by dimsumthinking** [comment]
Thank you - this is fixed for the next release. Thanks for raising the issue.
