### ISSUE TITLE
Various items discovered in Version 0.8

### ISSUE THREAD

**Issue by MikeLoh** [editorscut/ec008-swift-kickstart-2#101]
Following are items I noticed in reading the book. BTW, very good text for experienced developers - thank you for writing it.

Chapter 3: Section 6: Page 106
in func revenue, use Double, should this not be USDollars?

Chaper 3: Section 6: Page 107
same as above

Chapter 3: Section 10: Page 121
Should .urlforImageResources("Kickstart.jpg") not be .url(forResource: "Kickstart", withExtension: "jpg")?

Chapter 3: Section 10: Page 121
Little further down same as previous note when indicated type returned by urlForImageResource()

Chapter 3: Section 10: Page 121
Last line, same issue.

Chapter 3: Section 10: Page 122
Once again .usrForImageResource needs update

Chapter 5: Section 2 Page 200
in func color(from ..., do you need to remove word from? Occurs twice on page and once  more on page 201

Chapter 5: Section 2 Page 201
uiColor change to Color? Occurs several times on page.

Chapter 4: Section 2 Page 202
"It's kind of cool to see the feedback along with the actual color on the right side of the playground as a visual cue that we're getting the correct color back." - On my Xcode I did not see this, I had to Show Result to see the color. Could be just an option setting in Xcode that I could not find. Do you need to tell us how to set option?

Chapter 5: Section 3: Page 207
"...and for paintBrush, we get a red circlef." - typo.

Chapter 5: Section 4: Page 210
what is swatch()?

Chapter 5: Section 4: Page 211
crayon.circle() and paintBrush.circle() is not in provided code.

Chapter 5: Section 7: Page 225
wutgg - typo

Chapter 6: Section 2: Page 255
"Enumerations supported only computed properties." - this concept is repeated from previous sentence.

Chapter 6: Section 4: Page 265
Should lines:
  private(set) var x: Double
  private)set_ var y: Double
not be blue text?

Chapter 7: Section 6: Page 320
in code section \(hometown) actually shows compiler warning. Considering normally you point these out - should that be added?

Chapter 7: Section 6: Page 320
The extension Attendee section does not exist in code downloaded.

Chapter 10: Section 12: Page 487
"In the next chapter we create our own Sequence types." - I did not notice this in next chapter. Did I miss something?

Chapter 11: Section 4: Page 504
Forecast.count - downloaded code just has .count

**Comment by dimsumthinking** [comment]
Thank you! These are great. I will do another pass at the book soon and apply these errata.

**Comment by dimsumthinking** [comment]
Thank you - I think I have fixed all of these for today's release
