### ISSUE TITLE
Wrong label

### ISSUE THREAD

**Issue by thuroe** [editorscut/ec008-swift-kickstart-2#104]
Chapter 7 Classes
Section 5 Methods
Paragraphe final

« Before you forget, go back and remove the final keyword from the **ConferenceAttendee** definition of the nameBadge() method.  »

Should be 
« Before you forget, go back and remove the final keyword from the **Attendee** definition of the nameBadge() method.  »

.

**Comment by editorscut** [comment]
Thank you - fixed
