### ISSUE TITLE
Missing range declaration

### ISSUE THREAD

**Issue by thuroe** [editorscut/ec008-swift-kickstart-2#105]
Chapter 9,
Section 2 
Optionals

You describe the range used in the code but the declaration of the  Forecast struct does not contain the declaration of the range.
Adding the below line to the declaration of Forecast allow for the compilation of the code in the chapter
**_public static let range = 0..<count_**

**Comment by editorscut** [comment]
Thank you - fixed in the Swift Playgrounds Start code
