### ISSUE TITLE
Roadmap part count is off

### ISSUE THREAD

**Issue by richardalbury** [editorscut/ec008-swift-kickstart-2#108]
**Road Map** (Chapter 1, section 6, page 52) states "You can think of the book as falling into roughly two parts." and then goes on to list **three** parts.

**Comment by richardalbury** [comment]
Also, in the **Chapter 9: Errors** overview, it says "In this final chapter" when there are two more chapters after this one.

**Comment by editorscut** [comment]
Thank you - as a former mathematician that's embarrassing!

Fixed
