### ISSUE TITLE
Chapter 4: Section 5 - typo in output

### ISSUE THREAD

**Issue by sirshannon** [editorscut/ec008-swift-kickstart-2#11]
<img width="613" alt="screen shot 2016-12-25 at 4 46 32 pm" src="https://cloud.githubusercontent.com/assets/3629297/21472997/cdc22f1c-cac1-11e6-874d-5e086f32c256.png">

yField.text output (last line of screenshot) should also be "y"

(Book version 0.2 from Gumroad)

**Comment by dimsumthinking** [comment]
Thank you -fixed for next week's release (sigh - that was the whole point of this example - sorry for the typo)
