### ISSUE TITLE
Chapter-11 Reduce section, referencing wrong method

### ISSUE THREAD

**Issue by georgevlahos** [editorscut/ec008-swift-kickstart-2#110]
CHAPTER 11 : SECTION 9

A Swift Kickstart (Kindle Location 11390). Dim Sum Thinking. Kindle Edition. 

_We use reduce() the same way. Here are calls to reduce() with two parameters, a trailing closure, **and another trailing closure without using reduce()**. In each case, the result is $211.74._

Did Daniel mean to say 
_and another trailing closure without using **combine()**_
?

**Comment by editorscut** [comment]
Thank you - yes that is what I meant. Fixed.
