### ISSUE TITLE
Chapter 5 : Section 4 - Playground missing swatch method?

### ISSUE THREAD

**Issue by sirshannon** [editorscut/ec008-swift-kickstart-2#12]
Judging from the playground code + text from previous sections and the text in Chapter 5 : Section 4, it looks like the starter code in this section's playground should include the swatch() method. I'm not 100% sure about this.

(Book Version 0.2 from Gumroad)

**Comment by dimsumthinking** [comment]
Thank you - this was missing in the text of the book as well. Fixed in multiple places for next week's release
