### ISSUE TITLE
Chapter 4 : Section 1 - Smallest of code formatting issues (or not an issue)

### ISSUE THREAD

**Issue by sirshannon** [editorscut/ec008-swift-kickstart-2#13]
This is so small that I didn't think I should mention it but when I read through books on languages I don't know, one thing I look for is code formatting conventions. I'm firmly in the "when in Rome" camp and try to format each language I use in generally accepted manner of that language.  When I saw the line `primes = [2,3,5,7]` without spaces after each comma, it stuck out as being different than previous arrays in the book but I wasn't sure. Since then, I think every comma-separated list in the book has had a space after each comma so I have to mention it or it'll bother me forever :)
<img width="588" alt="screen shot 2016-12-27 at 9 42 35 am" src="https://cloud.githubusercontent.com/assets/3629297/21501859/8c43a440-cc19-11e6-90f8-ea71e3f1dd8c.png">

(Book Version 0.2 from Gumroad)

**Comment by dimsumthinking** [comment]
Thank you - you're right - there was an inconsistency with the way I formatted the String array. Fixed for next week's release.
