### ISSUE TITLE
Chapter 6 : Section 9 and Chapter 6 : Section 10 - incorrect section headers

### ISSUE THREAD

**Issue by sirshannon** [editorscut/ec008-swift-kickstart-2#14]
Chapter 6 : Section 9 is mislabeled as Chapter 8 : Section 9
Chapter 6: Section 10 is mislabeled as Chapter 6: Section 11

(Book Version 0.2 from Gumroad)

**Comment by dimsumthinking** [comment]
Thank you - fixed
