### ISSUE TITLE
Chapter 7 : Section 2 - Default Playground does not match text

### ISSUE THREAD

**Issue by sirshannon** [editorscut/ec008-swift-kickstart-2#15]
The default playground code shown in the book for Chapter 7 : Section 2 has Attendee.name as a let constant. We try to change it and get an error so the next step is to change let to var.
<img width="628" alt="screen shot 2016-12-27 at 3 39 00 pm" src="https://cloud.githubusercontent.com/assets/3629297/21507967/ef20314c-cc4a-11e6-9c8b-3eb02849a656.png">
The actual code in the playground already has Attendee.name as a var:
<img width="294" alt="screen shot 2016-12-27 at 3 38 40 pm" src="https://cloud.githubusercontent.com/assets/3629297/21507974/004be8e4-cc4b-11e6-9503-be287e72c164.png">

(Book Version 0.2 from Gumroad)

**Comment by dimsumthinking** [comment]
Thank you - adjusted the code download as you suggest. Fixed in next release
