### ISSUE TITLE
Chapter 7: Section 9 - Incorrect default code in Mac Playground

### ISSUE THREAD

**Issue by sirshannon** [editorscut/ec008-swift-kickstart-2#16]
Initial code in the book's Chapter 7: Section 9 (Lazy Loading) is
`var location = Location(city: "San Francisco")`

but code in the Mac Playground already has location as a lazy property:
`lazy var location = Location(city: "San Francisco")`

Sorry, I can not get this code to appear formatted correctly :/

**Comment by dimsumthinking** [comment]
Thank you - fixed in the download.
