### ISSUE TITLE
Typo in variable name tempGreeting

### ISSUE THREAD

**Issue by dfreniche** [editorscut/ec008-swift-kickstart-2#171]
A Swift Kickstart, 2nd Ed. v1.1 for Swift 5.5
PDF: page 135
Chapter 3: Variables and Constants
Using Variables and Constants
The Takeaway

> In this example, no one can reach in and modify `tempGreeting`

In the code listing above, variable is called `response`

**Comment by editorscut** [comment]
Thank you - I apologize that it's been so long but I'm finally updating the book (for the final time) and have made this correction.
