### ISSUE TITLE
[TYPO] Chapter 4: Collections | Section 1: Create arrays

### ISSUE THREAD

**Issue by jfdoradotr** [editorscut/ec008-swift-kickstart-2#172]
## Book Details

| Edition | Version | Released |
| --  | --  | --  |
| 2nd | 1.1 | July 2021 |

## Description

On subsection **Element access** on the first paragraph

> “Let's access the ith element of an array using square bracket notation...”

Is **ith** correct or should it be a position such as _first/third_?

**Comment by editorscut** [comment]
It was correct but I've rewritten that paragraph to be more clear. Thank you for raising this issue and I apologize that this is the first book rewrite since then. Thank you.
