### ISSUE TITLE
Error in highlighting colors?

### ISSUE THREAD

**Issue by dfreniche** [editorscut/ec008-swift-kickstart-2#173]
A Swift Kickstart, 2nd Ed. v1.1 for Swift 5.5
PDF: page 192
Chapter 4: Collections
Appending to Arrays
 
In this code:
```
var evens = [4, 10, 16] 
evens[1] = 2 
evens.append(8) 
evens += [12, 6, 10] 
```

In the last line `evens += [12, 6, 10] ` only `6, 10` appear highlighted. Any good reason for this?

**Comment by editorscut** [comment]
There was - but as it was confusing I'll highlight the entire array. It used to be 

evens += [12, 6, 10] so the only change is , 6, 10
