### ISSUE TITLE
Book Version 1.1, Chapter 3, Section 5, Page 95 — Function name “hello” should be “greetings”

### ISSUE THREAD

**Issue by ToffeeBar** [editorscut/ec008-swift-kickstart-2#174]
Currently reads, “I said the types of greetingFunction and **hello** are mostly the same.”
Seems like it should be, “I said the types of greetingFunction and **greetings** are mostly the same.”

Following that, this related code snippet should changed:

`let greetingFunction = hello`

to:

`let greetingFunction = greetings`

**Comment by dimsumthinking** [comment]
Thank You

**Comment by editorscut** [comment]
I've finally applied this fix and will be releasing it. Thanks again
