### ISSUE TITLE
Chapter 3: Section 2: Page 131 - closing tag

### ISSUE THREAD

**Issue by georgeandrews** [editorscut/ec008-swift-kickstart-2#18]
<img width="576" alt="screen shot 2017-01-06 at 1 35 02 pm" src="https://cloud.githubusercontent.com/assets/175664/21730362/02422bb4-d415-11e6-897a-91f4a70b6140.png">

It appears a tag may not be properly closed: ```var>```

**Comment by dimsumthinking** [comment]
Thank you. This is fixed for next week's release.
