### ISSUE TITLE
v1.2, chap 8, section 10 "More Access Levels", subsection 1 "Privately settable/publicly gettable" ¶ 11 (sample)

### ISSUE THREAD

**Issue by oliverlangan** [editorscut/ec008-swift-kickstart-2#180]
(This is counting each sample content as a single paragraph)

The last sample, which includes the comment "Don't actually make this change" has two small issues.
1. it shows the wrong file... it should be `08Protocols/10MoreAccessLevels/Sources/GettableNames.swift`
2. it doesn't show the code that would be deleted, in strikethrough. it should be:
    ~public~ private(set) var name: String

**Comment by editorscut** [comment]
Thank you - I've made both changes. I should be ashamed of myself.
