### ISSUE TITLE
v1.2, chap 11, section 1 "Types", subsection 4 "A containing type", ¶ 12 (last example) contains incorrect variable name

### ISSUE THREAD

**Issue by oliverlangan** [editorscut/ec008-swift-kickstart-2#182]
The last example in this section uses the internal variable `appPrice` in the function signature, but `price` in the body of the function.

The code would still run, since `price` is defined outside the function and so still available.

**Comment by editorscut** [comment]
Thank you - I missed that on this pass. Thank you for reporting it. It's fixed now.
