### ISSUE TITLE
Chapter 3: Section 8: Page 167 - Incorrect type

### ISSUE THREAD

**Issue by georgeandrews** [editorscut/ec008-swift-kickstart-2#19]
<img width="556" alt="screen shot 2017-01-06 at 1 37 56 pm" src="https://cloud.githubusercontent.com/assets/175664/21730460/6ec20160-d415-11e6-9e52-6527d84d21e4.png">

Should ```Int?``` be ```String? ``` here?

**Comment by dimsumthinking** [comment]
Thank you - fixed for next week's release.
