### ISSUE TITLE
Small typo - Release 0.2, Chapter 1, Section 1

### ISSUE THREAD

**Issue by elitree** [editorscut/ec008-swift-kickstart-2#2]
Page 19/342:  there's an extra comma in this sentence...

"If you don't see console output as you work your way through various examples in this book,, click the blue triangle to run the playground again."

(Thanks for updating the book to Swift 3! Love this book!)

**Comment by dimsumthinking** [comment]
Thank you for finding all of these and taking the time to let me know - this will be fixed in the next release

**Comment by dimsumthinking** [comment]
Fixed - this will be in next week's release.
