### ISSUE TITLE
Chapter 4: Section 5: Page 228 - Grammar

### ISSUE THREAD

**Issue by georgeandrews** [editorscut/ec008-swift-kickstart-2#22]
<img width="527" alt="screen shot 2017-01-06 at 1 45 32 pm" src="https://cloud.githubusercontent.com/assets/175664/21730689/74782e9e-d416-11e6-9a8b-70154f5baaac.png">

Grammar: Do you mean ```for both xField and yField```?

**Comment by dimsumthinking** [comment]
Yes thank you. Fixed for next week's release
