### ISSUE TITLE
Chapter 4: Section 6: Page 245 - Incorrect types

### ISSUE THREAD

**Issue by georgeandrews** [editorscut/ec008-swift-kickstart-2#23]
<img width="554" alt="screen shot 2017-01-06 at 1 49 28 pm" src="https://cloud.githubusercontent.com/assets/175664/21730818/157b1f04-d417-11e6-8748-d33f856e36fa.png">

Should this instead be:

>“We get a runtime crash because badNumbers[3] is ```a String``` and can't be cast to ```an Int```.”

**Comment by dimsumthinking** [comment]
Yes - thank you. Fixed for next week's release.

**Comment by dimsumthinking** [comment]
George - may I add your name to credits for submitting errata - if so please email me with how you would like to be listed
