### ISSUE TITLE
Chapter 5: Section 1: Page 284 - Missing instruction

### ISSUE THREAD

**Issue by georgeandrews** [editorscut/ec008-swift-kickstart-2#25]
<img width="571" alt="screen shot 2017-01-06 at 1 55 00 pm" src="https://cloud.githubusercontent.com/assets/175664/21730976/cd2e832a-d417-11e6-9296-bbb20789e5a9.png">

Reader is never told to set color to ```.blue```.

**Comment by dimsumthinking** [comment]
Thank you - fixed and the value is also corrected to green to match the instructions.
