### ISSUE TITLE
Chapter 5: Section 12: Page 352 - Missing content

### ISSUE THREAD

**Issue by georgeandrews** [editorscut/ec008-swift-kickstart-2#28]
<img width="568" alt="screen shot 2017-01-06 at 2 01 55 pm" src="https://cloud.githubusercontent.com/assets/175664/21731186/c0304fae-d418-11e6-9594-8a2da63469ed.png">

In Chapter 5, I could not find where we built error types.

**Comment by dimsumthinking** [comment]
Thank you - I've moved this to a brand new chapter 12 which will be included in this release. Removed this sentence
