### ISSUE TITLE
Chapter 6: Section 2: Page 363 - Internal name not provided

### ISSUE THREAD

**Issue by georgeandrews** [editorscut/ec008-swift-kickstart-2#29]
<img width="577" alt="screen shot 2017-01-06 at 2 03 59 pm" src="https://cloud.githubusercontent.com/assets/175664/21731257/1b7e66ca-d419-11e6-9ab9-88c929e288db.png">

An internal name is not provided in the example code in book.

**Comment by dimsumthinking** [comment]
fixed - thanks in next release
