### ISSUE TITLE
Chapter section headers incorrect - Release 0.2, Chapter 6

### ISSUE THREAD

**Issue by elitree** [editorscut/ec008-swift-kickstart-2#3]
The final 2 sections of Chapter 6 appear to have incorrect numbers:

1. Page 261/342, the Custom Operators section, is marked Chapter 8 Section 9; this should be Chapter 6 Section 9.
2. Page 265/342, the chapter conclusion, is marked Chapter 6 Section 11; this should be Chapter 6 Section 10.

**Comment by dimsumthinking** [comment]
Arrggghhh - thank you. I will fix these for the next release

**Comment by dimsumthinking** [comment]
Thank you this is fixed for next week's release.
