### ISSUE TITLE
Chapter 6: Section 3: Page 371 - Incorrect instruction

### ISSUE THREAD

**Issue by georgeandrews** [editorscut/ec008-swift-kickstart-2#30]
<img width="571" alt="screen shot 2017-01-06 at 2 06 54 pm" src="https://cloud.githubusercontent.com/assets/175664/21731328/79182adc-d419-11e6-8d43-e3349c14903c.png">

Should it instead read "change point from a ```let``` to a ```var```"?

**Comment by dimsumthinking** [comment]
Thank you - fixed for next release
