### ISSUE TITLE
Chapter 6: Section 6: Page 387 - Grammar

### ISSUE THREAD

**Issue by georgeandrews** [editorscut/ec008-swift-kickstart-2#32]
<img width="554" alt="screen shot 2017-01-06 at 2 13 00 pm" src="https://cloud.githubusercontent.com/assets/175664/21731502/4d81a712-d41a-11e6-8a1a-e8a2c2532526.png">

I hate to do this: ```their```

**Comment by dimsumthinking** [comment]
I'm so glad you did - I'm so embarrassed. Fixed.
