### ISSUE TITLE
Chapter 7: Section 2: Page 423 - Misspelling

### ISSUE THREAD

**Issue by georgeandrews** [editorscut/ec008-swift-kickstart-2#33]
<img width="588" alt="screen shot 2017-01-06 at 2 14 56 pm" src="https://cloud.githubusercontent.com/assets/175664/21731564/90db6cb4-d41a-11e6-8632-f6371eab2518.png">

Output should be ```Kimberli```.

**Comment by dimsumthinking** [comment]
Thank you - fixed
