### ISSUE TITLE
Chapter 8: Section 2: Pages 498 and 499 - Difficult to follow

### ISSUE THREAD

**Issue by georgeandrews** [editorscut/ec008-swift-kickstart-2#37]
This section refers to ```Vertex```, ```Size```, and ```Rectangle```. On the bottom of page 498 we wrap up appropriate updates to ```Vertex``` and then on page 499 it appears we transition to updating ```Rectangle```. However, there is no language used to describe this transition.

Also, code on page 499 appears to be from the ```Rectangle``` struct, but it is hard to tell without additional context.

**Comment by dimsumthinking** [comment]
Man that was horrible - I'm so sorry. I've tried to rewrite the section to be more clear. Thanks for calling it out. Fixed? for next version
