### ISSUE TITLE
Release0.2 Chapter 3 Section 1 people's type is shown as String, not [String]

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#41]
“for person in people {
The type is reported as [String]. ”

When doing on Option click on people in there, it is only defined as String, not [String]. 
(Xcode 8.2.1 on my machine)
I see your point: it should be [String]. Maybe the inference is more problematic with a variadic parameter. Or understanding it as an array is easier but under the hood, it is not that  way. 

Excerpt From: Steinberg, Daniel H. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
I really don't know what to do about this one. There's a bug in Xcode and I've filed a radar. It used to work the way I described but currently doesn't. I've changed the wording from "Xcode is reporting this" as to "Xcode should be reporting this as".
