### ISSUE TITLE
Release 0.2 Chapter 3 Section 1 Did you mean "person" instead of "people"? 

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#42]
“I also told you that personvar> has to be of type String because it is an element of the people Array. You can select either of these occurrences of people to confirm that its type is correctly inferred to be a String.”

Did you mean "either of these occurrences of person to confirm..."? 
person is recognized as a String by Option click.

Excerpt From: Steinberg, Daniel H. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Yes thank you. Fixed for next week's release
