### ISSUE TITLE
Release 0.2 Chapter 3 Section 2 Capitalized first word after a :

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#43]
“but it does call out the key difference between let and var: Once you've assigned ”

"var" is followed by a colon. "Once" should not be capitalized then at the start of the next sentence? 

Excerpt From: Steinberg, Daniel H. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
That's what I thought but my editor has consistently asked me to cap them.
