### ISSUE TITLE
Release 0.2 Chapter 3 Section 7. simpleProduct should be literalProduct

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#45]
“The result is that simpleProduct is the product of the Doubles 5.0 and 3.7 and so the product is a Double.”

literalProduct has been defined as a constant just above. It is not called simpleProduct.

Excerpt From: Steinberg, Daniel H. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - fixed for next week's release
