### ISSUE TITLE
Release .02 Chapter 3 Section 7 Extra "we" 

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#46]
“We we can safely multiply the two Doubles to get another Double.
let literalProduct = 5 * 3.7 ”

"We" is repeated: maybe meant as "We then can safely..."

Excerpt From: Steinberg, Daniel H. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - fixed for next week's release
