### ISSUE TITLE
Release 0.2 Chapter 3 Section 11 Repetition of the word "later"

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#47]
Second paragraph. Second sentence. 
“ If we take that approach, then we must later set its value later, before using the variable.”

The word "later" is there twice.  

Excerpt From: Steinberg, Daniel H. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - fixed for next week's release.
