### ISSUE TITLE
Release 0.2 Chapter 4 Section 1 Typo: extra "the"

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#48]
3rd paragraph has an extra "the" 

“ It reminds us of **the** these three things:”

Excerpt From: Steinberg, Daniel H. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - how do I miss the these? Fixed for next week's release.
