### ISSUE TITLE
Release 0.2. Chapter 4 Section 3. 12 is added twice in the array from the code

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#49]
“evens += [12]
evens
[4, 2, 16, 8, 12]”

We added 12 to the end of the array, but in the following code, we add it again. 
The rest of the section shows it not to be the intent. 

“evens += [12, 6, 10]
evens
[4, 2, 16, 8, 12, 6, 10] ”

Excerpt From: Steinberg, Daniel H. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
I've clarified the prose. The syntax coloring was supposed to indicate that I was changing one to the other - but I wasn't clear. Thank you for calling this out. Fixed for next week's release.
