### ISSUE TITLE
Link to blog is broken

### ISSUE THREAD

**Issue by sdevore** [editorscut/ec008-swift-kickstart-2#5]
the link in the book to your blog points to http://dimsumthinking.com/blog/ which gives a 500 error.  The link from your home page is http://dimsumthinking.com/Blog/index.html  could be the lower case `blog` is causing the error

**Comment by dimsumthinking** [comment]
Thank you

I refactored my web page and forgot to make the change in the book. Thanks this will be fixed in the next release.

**Comment by dimsumthinking** [comment]
This is fixed and will be in next week's release. Thank you
