### ISSUE TITLE
Release 0.2 Chapter 4 Section 5 Confused about order of code

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#50]
There is a discrepancy in the order of the code shown at the beginning of the section. 
The book starts with var declaration then suddenly goes to let declarations, while the code in the bundle starts with the let declaration and then goes on to using var.

**Comment by dimsumthinking** [comment]
I think I've called out where the change occurs better - I don't see the discrepancy with the code bundle but I've highlighted the code better (I think). Thanks - this is in next week's release.
