### ISSUE TITLE
Release 0.2 Chapter 4 Section 9 A warning shows up for using numbers[key]

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#51]
“for key in numbersKeys {
    print(key, ":", numbers[key])
}”
With this code (in Xcode 8.2.1), I get a warning 
"Expression implicitly coerced from 'Int?' to Any

Force unwrapping that is shown afterwards remove the warning. 
It must have been your point: it is just that you usually point out if we are supposed to see a warning.
(which I find a good practice to get used to what this or that warning, error message means)

Excerpt From: Steinberg, Daniel H. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - I added the warning and discussed how to move from that to the "fixed" version. Thanks again - fixed for next week's release.
