### ISSUE TITLE
Release 0.2 Chapter 4 Section 10 The count of odds should be reflected as 4 after removing 7

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#52]
“odds.insert(7)
odds.remove(7)

odds.count
5
odds”

It shows 5 as the count while it should be 4. The code downloaded is correct on this, showing 4.

Excerpt From: Steinberg, Daniel H. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - fixed for next week's release
