### ISSUE TITLE
Release 0.2 Chapter 5 Section 1. Feedback is green not blue

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#53]
“Since crayon is known to be of type Color, once you type the ., you'll again get the popover suggesting the completions. The feedback on the right side confirms that crayon now has the value blue.”

Last word: "blue". 
crayon has been set to green in the code just above crayon = .green

Excerpt From: Steinberg, Daniel H. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - fixed for next release
