### ISSUE TITLE
Release 0.2 Chapter 5 Section 4 Possessive "its" instead of "it's"

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#54]
“Because it's value is calculated on the spot, a computed property must be declared to be a var and not a let.”

Excerpt From: Steinberg, Daniel H. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - these make e feel so stupid. Fixed for next release
