### ISSUE TITLE
Release 0.2 Chapter 5 Section 4 "chage" should be replaced by "change". Missing "n"

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#55]
“For example, chage crayon from this:
crayon.uiColor()”

Missing "n" in "chage" to make it "change"

Excerpt From: Steinberg, Daniel H. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - I've made the chage. Fixed for next release

**Comment by nwreg** [comment]
I see what you did there! 😉
