### ISSUE TITLE
Release 0.2 Chapter 6 Section 1 "it's" should be the possessive its

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#56]
“In it's current form, this Vertex struct is absolutely useless.”

Excerpt From: Steinberg, Daniel H. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Another one! Thank you. Fixed for next release
