### ISSUE TITLE
Release 0.2 Chapter 7 Section 6 Might need to add the extension code

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#58]
“To fix this, set the default value to nil. Here's the updated version of Attendee.

class Attendee {
    let name : String
    let hometown : String?
    
    init(name: String, hometown: String? = nil) {
        self.name = name
        self.hometown = hometown
    }
    func nameBadge() -> String {
        return "Hello, I'm \(name) from \(hometown)."
    }
}
”
Should not we still have the code for the extension here? 
We got rid of the TutorialAttendee code from the previous section, but nameBadge is called in the extension.

Excerpt From: Steinberg, Daniel H. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - I've added the extension code here.
