### ISSUE TITLE
Release 0.2 Chapter 7 Section 7 Second sentence unclear to me.

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#59]
“We used a failable initializer when we tried to create an instance of an enumeration from a raw value. We saw that there was a possibility that there's no such case corresponding to the raw value nothing is created, if there's a valid case then we get a valid instance of the enumeration wrapped in an Optional.”

Maybe adding "and" and cutting it in two sentences would make sense:
" there's no such case corresponding to the raw value and nothing is created.
If there's a valid case then we get ...."

Excerpt From: Steinberg, Daniel H. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - I've added a couple of sentences to try to make the path through this more clear. Thanks again.
