### ISSUE TITLE
Release 0.2 Chapter 1 Section 1 Mac Quickstart: the Show Result icon is rectangular for me

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#6]
The Show Result icon, the circle within a circle, actually shows up as a rectangle within a box. 
But the icon to dismiss it still shows as a black filled circle with an X in it. 
I added two screenshots below.

For info, I am on Sierra10.12.2 Beta (16C63a) and Xcode Version 8.2 (8C38). 
Changing the Fonts and Colors (from my usual Dusk) doesn't change this. Modifying the size of the window or of the right side column does not affect it.

Guessing there might be a difference of Xcode version. 
<img width="294" alt="screen shot 2016-12-13 at 5 51 56 pm" src="https://cloud.githubusercontent.com/assets/8108318/21213493/8f8b6914-c249-11e6-9fab-415ac9b0283a.png">
<img width="207" alt="screen shot 2016-12-13 at 5 59 53 pm" src="https://cloud.githubusercontent.com/assets/8108318/21213494/8fa7184e-c249-11e6-8f9c-e36b6683a81d.png">

**Comment by dimsumthinking** [comment]
Thank you - reshot all of the images in this section. In next release
