### ISSUE TITLE
Release 0.2 Chapter 8 Section 1 Subject is plural?

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#61]
Right near the start

“ Imagine that they each has a method called movedHorizontally()”

Shouldn't it be "have a method... " instead of "has a method.."? The subject is "they" not "each". 

Excerpt From: Steinberg, Daniel H. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - good grammar catch.
