### ISSUE TITLE
Release 0.2 Chapter 8 Section 5 . "shiftedLeftPoint" should be "shiftedLeftVertex

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#64]
Last paragraph of the section

“Unfortunately, shiftedLeftPoint is a Movable and not a Vertex and shiftedLeftRectangle is a Movable and not a Rectangle. "

We didn't use shiftedLeftPoint, but from the sentence, it could/should be shiftedLeftVertex.

Excerpt From: Steinberg, Daniel H. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - fixed
