### ISSUE TITLE
Release 0.2 Chapter 8 Section 9 Missing space between "an" and "internal access"

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#65]
“Without the keyword public, this is exactly the init() that's automatically created for us. Unfortunately, that init() has aninternal access level. ”

Excerpt From: Steinberg, Daniel H. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - fixed

Thank you for all of your help with this release!

**Comment by nwreg** [comment]
You are so welcome. Happy to see the next version in the works. ( and stumbling onto things like "on the third hand..." Ch 8 I believe. )

**Comment by dimsumthinking** [comment]
Code is checked in for chapters 9 - 12. Will submit updated version tomorrow or Monday. All that's left is the part I'm really bad at - marketing copy!

**Comment by nwreg** [comment]
All the best for the push for the marketing copy. Just makes it yours. ;-) What's in Ch 9-12, if I may ask now?
