### ISSUE TITLE
Release 0.3 Chapter 9 Intro: missing space in "usingnon-mutating" between using and non-mutating

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#66]
Last paragraph of intro.

 “We cap the chapter with a look at a container with methods that add and remove elements by first using mutating methods, then usingnon-mutating methods and finally using generic methods that operate appropriately on parameters of different types.”

Separate "using" from "non-mutating"

Excerpt From: Daniel H Steinberg. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - fixed in the next release.
