### ISSUE TITLE
Release 0.3 Chapter 9 Intro: possessive form "its" instead of "it's parameters"

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#67]
Last sentence of introduction

“Let's start with a look at a simple function and it's parameters.”

"its" instead of "it's"

Excerpt From: Daniel H Steinberg. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - fixed
