### ISSUE TITLE
Release 0.3 Chapter 9 Section 6 Missing "to" in "It would be nice get feedback"

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#69]
“It would be nice get feedback from the playground that includes the contents of the Model and not just the word Model.”

Missing "to" between "nice" and "get"

Excerpt From: Daniel H Steinberg. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you fixed
