### ISSUE TITLE
Chapter 2, Section 3: Incorrect body of func hello(name:String)->String

### ISSUE THREAD

**Issue by aijaz** [editorscut/ec008-swift-kickstart-2#7]
Chapter 2, Section 3: 

```
func hello(name: String) -> String {
    return "Hello, \(name)!"
}
```

should be: 

```
func hello(name: String) -> String {
    return "Hello, someone!"
}
```

to match the surrounding explanation/context. 

<img width="576" alt="napkin 12-21-16 8 33 50 pm" src="https://cloud.githubusercontent.com/assets/795100/21413420/cc9e666c-c7bc-11e6-8d87-1b92deebf2d7.png">

**Comment by dimsumthinking** [comment]
Thank you! This is fixed for next week's release.
