### ISSUE TITLE
Release 0.3 Chapter 10 Section 4 Last sentence unclear to me

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#70]
“ In the section after that we expand the apply() function apply the same function to every member of an Array.”

Excerpt From: Daniel H Steinberg. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
thank you - fixed
