### ISSUE TITLE
Release 0.3 Chapter 10 Section 8 Some intermediary code is shown in the playground but not in the text

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#71]
The following code is shown in the code on the playground after the use of keep() but before we define  revenueForMoreThan25. 
However, the text does not show this. 

let moreThan25 = numberSold.filter{$0 > 25}
moreThan25

let weekdaySales = dailyNumberSold.filter{!weekendDays.contains($0.key)}
weekdaySales

**Comment by dimsumthinking** [comment]
Thanks - I didn't understand this at first - what was missing were the variables I was assigning the values to as the playground didn't reflect the results otherwise. Thanks for pointing this out - fixed.
