### ISSUE TITLE
Release 0.3 Chapter 10 Section 9 Extra "the" 

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#72]
“The element of the sequence is of type Iterator.Element and the the first parameter and return type of the combination function are of type Output. The return type of the reduce() method is also of type Output.”

First sentence has a double "the" before "first parameter".

Excerpt From: Daniel H Steinberg. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - fixed
