### ISSUE TITLE
Release 0.3 Chapter 10 Section 10 "languageDictionary" should be "dictionary" AND "Dictionary" should be lowercase

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#74]
“Check out **languageDictionary**. The keys are Strings and the values are Arrays of type [Language]. Let's map the **Dictionary** to create an Array from their values. The result will be an Array of Arrays.
”

Excerpt From: Daniel H Steinberg. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - fixed
