### ISSUE TITLE
Release 0.3 Chapter 10 Section 10. Unclear to me:  the term "lifts" in this context. 

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#75]
“The idea of map() is that if we have a function f that maps Element to Output, then map(f) lifts f to a map from [Element] to [Output].”

I thought it might refer to a mathematical term (quick search said yes) but I was not familiar with it so it confused me there. Is it like composing functions?
Anyhow, I don't know anything about category theory, but I think I got the jest of it. 

Excerpt From: Daniel H Steinberg. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
I tried - not sure if I succeeded
