### ISSUE TITLE
Release 0.3 Chapter 10 Section 9. General question about the Sources file in playground

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#76]
I can't quite recall if how to create Swift files in Sources file was covered in another part of the book. 

Then I realized that I was retyping the code in a new playground of my own, not the "empty" one you had provided. I have my own and the fully completed one you give. 
Therefore, mine was not done with Source files.
It's not a problem: I just realized that I was used the resources downloaded differently than what you probably had envisioned.

**Comment by dimsumthinking** [comment]
Thank you - is there something I should do? I am closing this but can reopen

**Comment by nwreg** [comment]
No. It works with the playgrounds you provided. It’s just that I had been stubborn and was typing my own playground as a way to remember things more. 

Sincerely, 

Regine
