### ISSUE TITLE
Release 0.3 Chapter 11 Intro Replace "a lot" by "a look"

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#77]
“We also take a **lot** at while let and explain how it supports fast enumeration in Sequences.”

Replace "lot" by "look" would be my guess.

Excerpt From: Daniel H Steinberg. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
thanks -fixed
