### ISSUE TITLE
Release0.3 Chapter 11 Section 6 End of section: code in playground has the call to use map()

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#78]
let mappedArrayFromSequence = sequence.map{$0}
mappedArrayFromSequence

This code is included in Sequence and Iterator playground page, even though, it is not used in the book. (remnants of last section I guess)

**Comment by dimsumthinking** [comment]
Fixed by adding it to the prose - the point was that these things still work even when we have a sequence created like this. Thanks
