### ISSUE TITLE
Chapter 2: Section 10 - incorrect function shown

### ISSUE THREAD

**Issue by sirshannon** [editorscut/ec008-swift-kickstart-2#8]
The hello func shown in this screenshot looks like it was pasted erroneously and the code should only demonstrate calling the function. The version of the func shown (naming the elements of the tuple) is introduced shortly after this.

<img width="620" alt="screen shot 2016-12-24 at 11 35 36 pm" src="https://cloud.githubusercontent.com/assets/3629297/21469735/ed484ce4-ca31-11e6-997c-c35e6d2fca4c.png">

(Book Version 0.2 from Gumroad)

**Comment by dimsumthinking** [comment]
Thank you - this is fixed for next week's release.
