### ISSUE TITLE
Release 0.3 Chapter 11 Section 8 "If  you try to do the following." could be connected to sentence before

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#80]
“Actually, this isn't quite how Arrays act. An Array would throw some sort of out-of-bounds error. If you try to do the following.

arrayFromSequence  // don't do this 
You'll get a fatal error with this message.”

The sentence "If you try to do the following." could either be connected to the sentence before. (removing the period)
Or it could go with the next sentence, "You'll get a fatal error with this message."

Excerpt From: Daniel H Steinberg. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - reworded it.
