### ISSUE TITLE
Release 0.3 Chapter 12 Section 3 "gt;" instead of '<" in code for the use of precondtion

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#81]
“extension Forecast {
    static func number(_ index: Int) -> String {
        precondition(index **gt;**= 0 && index < count, "Out of bounds")
        return Forecast()[index]
    }
}
”

"index **gt;**= 0" should be "index **<**= 0"

Sorry: for the use of precondition in the title above. Typed too fast...

Excerpt From: Daniel H Steinberg. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - fixed
