### ISSUE TITLE
Release 0.3 Chapter 12 Section 3 "eextension" starts with a double "e" 

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#82]
“**e**extension Forecast {
    static func number(_ index: Int) -> String {
        if index < 0 || index >= count {
            assertionFailure("\(index) is out of bounds. "
                + "Must be between 0 and \(count).")
        }”

Excerpt From: Daniel H Steinberg. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
thanks fixed
