### ISSUE TITLE
Release 0.3 Chapter 12 Section 4 Extra word "it" in second sentence

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#83]
“To start, we're going to define our own Error. An Error is anything that's marked to conform to the Error protocol. Here, we create our Error **it** with a struct named SubscriptOutOfBoundsError.”

Excerpt From: Daniel H Steinberg. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
thank you - fixed
