### ISSUE TITLE
Release 0.3 Chapter 12 Section 4 "tryed" 

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#84]
“Here's how we use try. In a moment you'll see that we shouldn't use try if the action being **tryed** can fail.
”
I see the keyword **try** is incorporated and conjugated, but at first, I could only see it as a mistake instead of "tried". It threw me off (Oh my, it's hard to avoid puns in this one!) and I had to look very carefully to see the color and topography of the "try" letters. (old eyes) 

So it is correct, but jarring (to me). 

Excerpt From: Daniel H Steinberg. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - I reworded it to "attempting to "try""

I hope this hasn't been too painful and that the book has been worth all your time. I really appreciate all the help you've provided.

**Comment by nwreg** [comment]
Of course not it's not painful! I am trying to finish Ch 12 today or tomorrow... you are catching up fast.
Glad to be of help. (And helping myself at the same time)

Regine
