### ISSUE TITLE
Release 0.3 Chapter 12 Section 8 Wrong calculation in book code for excess

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#85]
“ let excess = index **+** Forecast.count + 1”

Shouldn't it be 
let excess = index **-** Forecast.count + 1 
as shown in the completed playground for this section?

It does result in the answer 26 for forecastNumber(20), which was supposed to be "greater than 5 by 16" in the book.

It also affects the results shown in the book in the next section, 9. 

Excerpt From: Daniel H Steinberg. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Yes, thank you - fixed.
