### ISSUE TITLE
Release 0.3 Chapter 12 Section 11 First bullet point unclear to me: missing word? And missing space between "of" and "Optionals"

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#86]
“Take advantage ofOptionals by together with try?.”

"ofOptionals" Should it be "of Optionals"?
Also, I am not sure what it meant in this point: is there a verb missing?

Excerpt From: Daniel H Steinberg. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
Thank you - I think I've fixed this.
