### ISSUE TITLE
Release 0.3 Chapter 8 Section 10 The passage about this being the end of the book is still there but now, you have 12 chapters

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec008-swift-kickstart-2#87]
“That brings us to the end of the book. I could write a chapter filled with closing material but I've never been a big fan of long goodbyes.

You've now seen enough Swift to write great apps.

Go ahead. What are you waiting for?”

This is at the end of Chapter 8, which used to be your last chapter, before you generously extended it. 
There is a conclusion at the end of Chapter 12 of the same kind. 

Excerpt From: Daniel H Steinberg. “A Swift Kickstart (Second Edition).” iBooks. https://itun.es/us/J4uNgb.l

**Comment by dimsumthinking** [comment]
oops - thank you. Fixed
