### ISSUE TITLE
Invalid Playground Book

### ISSUE THREAD

**Issue by robertcerny** [editorscut/ec008-swift-kickstart-2#88]
Hi,
I tried to open iPad version of "StartSwiftKickstart" playground but it's saying "Missing the DevelopmentRegion key in the manifest"

**Comment by dimsumthinking** [comment]
I’m sorry - I will look into this once iOS 11 final ships tomorrow and will update it by tomorrow afternoon. 

Sorry for the inconvenience.

Daniel

**Comment by dimsumthinking** [comment]
Thank you Robert this is fixed. FYI the docs for Version number told me to use 3.0 instead of 1.0 and this led to it looking for the DR key which is currently not documented.

I never could have found this without your kind help and carefully written issue.

Thank you,

Daniel
