### ISSUE TITLE
Release 0.5, Chapter (multiple), Section (multiple) - Code not rendering with styles in Chrome/FF

### ISSUE THREAD

**Issue by elitree** [editorscut/ec008-swift-kickstart-2#89]
When I open the book in Chrome or Firefox, code no longer seems formatted properly (code still looks good when I open it in Safari). I get some javascript errors when loading the book in gumroad's website with those browsers. Looking at the inspector, it's refusing to load stylesheets:

![2018-04-17 13_13_52-a swift kickstart](https://user-images.githubusercontent.com/602697/38885599-79267172-4241-11e8-88e3-98810cfba922.png)

Here's one of the javascript errors from the inspector:

```
read_epub-6c3eb7b3bfe160720c1ebf4dee4c464f495bda45f2123c314f6c7259226b9515.js:9 
Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Libre+Baskerville:400,700,400italic&subset=latin,latin-ext' 
because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline'
 https://s.ytimg.com https://ssl.p.jwpcdn.com https://assets.gumroad.com".

setStyle @ read_epub-6c3eb7b3bfe160720c1ebf4dee4c464f495bda45f2123c314f6c7259226b9515.js:9
```
*****

The Gumroad app seems to now crash when I try opening the book in there (iPhone 6s, iOS 11.3), though I don't think I've opened it there recently, so I'm not sure that's related.

Thanks so much for keeping this book up to date with the latest Swift features!  I love coming back to it.

-Eli

**Comment by dimsumthinking** [comment]
Eli,

I apologize but I think the issue is with Gumroad. I've just opened a couple of the books I've purchased from other authors and none of them are rendering correctly. If you download the epub or mobi does it look ok on your device?

**Comment by elitree** [comment]
Yes, things are fine in ePub/Mobi, as well as Mac Safari. Thanks for checking into it, I'll use one of those options going forward.
