### ISSUE TITLE
Release 0.7 Chapter 1, Let's Get Started, page 8 - copy edit

### ISSUE THREAD

**Issue by nathany** [editorscut/ec008-swift-kickstart-2#90]
Hi Daniel. Thanks for keeping your book updated. It's one of the only Swift 5 books I can find. I just received a print copy of version 0.7 which I'll be going through (I also have the ebook from Gumroad). Looking forward to learning Swift!

At the top of page 8, it says "an interactive environment in Xcode 9 and now on iOS" but later recommends Xcode 10. Maybe that should just say Xcode 10 throughout, or maybe Xcode 9 or greater? [of course Xcode 11 will be out soon enough]

In paragraph 5 of page 8 it says "OS X 10.14 Mojave" which should probably say macOS instead of OS X (anywhere through the book).

At the bottom of page 8 it says "As a result not only has all of the code ~~has~~ been updated..." It would read better without the second "has" there. I'd also suggest a comma after "As a result".

**Comment by editorscut** [comment]
fixed thank you
