### ISSUE TITLE
Release 0.7, Chapter 1, Section 1 - Xcode 10.3 changes?

### ISSUE THREAD

**Issue by nathany** [editorscut/ec008-swift-kickstart-2#91]
On page 11, it says "You should see this on your playground page."

However, I don't see the value "hello" on the right side until after clicking the triangle at the bottom, which is no longer blue in Xcode 10.3 on macOS Mojave 10.14.6.

I see there is an option in the menu as well, Editor > Run Playground or Shift-Command-Enter.  I don't any option to automatically run the playgrounds, but maybe I'm missing something?

At the end of page 12 you introduce the "console". The tooltip in Xcode 10.3 says "Show the debug area" and the Shift-Command-Y shortcut is under View > Debug Area > Show Debug Area in the menu. Did they change the name from console to debug area? (There's also an activate console option in the same menu, so Xcode is a bit confusing).

**Comment by dimsumthinking** [comment]
This is fixed - I'm not sure if I fixed it in response to this comment or it was there but the paragraph above should tell you to run the code.

As for the Debug area - I'll add a comment. Thank you
