### ISSUE TITLE
Release 0.7, Chapter 1, Section 1, page 14 - copy edit

### ISSUE THREAD

**Issue by nathany** [editorscut/ec008-swift-kickstart-2#92]
On page 14 it says "ThinkingInSwift directory" for the completed playgrounds. I think this should say SwiftKickstart directory or SwiftKickstart.zip?

Command-0 shows the file directory, but just noting that Apple calls this thing the "Navigator" and specifically the "Project Navigator" -- which would only matter if using the menus or if someone had switched to a different navigator without being aware of this.

Also on page 14, you refer to the "Source" (3x) and "Resource" (twice) directory. Minor nitpick, but in the actual playgrounds they are pluralized "Sources" and "Resources".

**Comment by editorscut** [comment]
fixed thank you
