### ISSUE TITLE
Release 0.7, Chapter 1, Section 4 - Links in Print

### ISSUE THREAD

**Issue by nathany** [editorscut/ec008-swift-kickstart-2#93]
Page 27 has a number of links, but I'm reading the print version of your book. 🤔

Would it be possible to include footnotes with the actual URLs below? Or could you put the links in parenthesis like you do for editorscut.com on page 29?

Some of the links are rather long, so a link shortener could help. I can recommend [bitly.com](https://bitly.com) (not affiliated with them, just a happy user). They allow custom domains with HTTPS for free, which is great. So instead of [bit.ly/programminggo](https://bit.ly/programminggo), I can use my own domain [yng.mn/programminggo](https://yng.mn/programminggo) for short links.

I'd like to suggest tweaking your wording with the print version in mind. So on page 27, instead of saying "Submit your errata here" just say "Submit your errata ([dmsm.dev/askerrata](https://dmsm.dev/askerrata))" or whatever URL you end up using.

P.S. I also bought the ebook on Gumroad, so I was able to click the links and submit errata here, but if I only purchased the print version I would be left Googling.

**Comment by nathany** [comment]
More links without URLs on page 29 (Chapter 1, Section 5).

**Comment by editorscut** [comment]
Thank you - you are right but in thinking it through I've decided this book will be digital only.
