### ISSUE TITLE
Release 0.7, Amazon listing

### ISSUE THREAD

**Issue by nathany** [editorscut/ec008-swift-kickstart-2#95]
Hey Daniel.

Btw, the [Amazon listing](https://www.amazon.com/dp/0983066981/ref=cm_sw_em_r_mt_dp_U_j2.ADbW6BGVKS) is a bit confusing as it makes reference to both Swift 5 and Swift 4.

> "This best-selling book gets experienced programmers up to speed quickly with Swift 5.Swift is Apple’s open-source programming language for writing everything from iOS apps to server side code. This new version is updated to **Swift 4**"

Had to look around to ensure it is indeed updated for Swift 5.

**Comment by editorscut** [comment]
Thank you - I will check this elsewhere as well. I've pulled the sale of this book through Amazon
