### ISSUE TITLE
Book versioning consistency

### ISSUE THREAD

**Issue by luvvie** [editorscut/ec008-swift-kickstart-2#96]
This is for the file entitled "SwiftKickstart2v0800.epub". Book title of "A Swift Kickstart".

On page 34 (with I consider authoritative), states "Version 0.8" and “This is the Swift 5.1 / Xcode 11 release.”

Page 8 seems to confirm this with: “Welcome to the Swift 5.1 release of the second edition...”

I question the correctness on page 1: “This is version 0.7 for Swift 5, Xcode 10, and iOS 12 released February 7, 2019.” All of this data seems to conflict with the two previous citations. I realize the horrible insignificance of this, but I cannot help myself.

**Comment by dimsumthinking** [comment]
Thank you - I have updated this for the next version.
