### ISSUE TITLE
Clumsily not listening to my own eyes.

### ISSUE THREAD

**Issue by luvvie** [editorscut/ec008-swift-kickstart-2#97]
Version 0.8, Page 61 (last page of Chapter 2, Section 4).

While double checking this issue before submitting, I was going to say that I believe the following line to be extraneous: “hello() above the line func hello(name: String) {.”

In reality, it is not extraneous.

Maybe some trivial re-wording "Move the line containing hello() as shown below." would not have tripped me up, but at this point I am going to say I misread that paragraph. The only purpose in submitting this issue would be asking the author for a quick revisiting. To reiterate, the book stands correct.

**Comment by dimsumthinking** [comment]
Thank you
