### ISSUE TITLE
No code completions for .urlForImageResource

### ISSUE THREAD

**Issue by ichbindaa** [editorscut/ec008-swift-kickstart-2#98]
Chapter 3: Section 10

`import SwiftUI
let fileURL = Bundle.main.urlForImageResource("Kickstart.jpg")`

it seems there is no such think like 

> .urlForImageResource()

 anymore in Swift 5.1.

instead I used `.url(forResource: "Kickstart", withExtension: "jpg")`

**Comment by dimsumthinking** [comment]
I just checked this and it compiles and runs on my machine. You need Swift 5.1 installed and need to have imported SwiftUI.

Please let me know if this doesn't work for you. It's a Mac playground so this most likely means it requires Catalina. It should work fine on an iPad running iOS 13.

**Comment by ichbindaa** [comment]
Hello, Daniel,
I checked again. I have a Mac with Catalina and Xcode version 11.2.1 (11B500). Xcode doesn't provide auto-completion for this feature and the context menu doesn't display it either.
`ErrorMessage: Value of type 'Bundle' has no member 'urlForImageResource'.`

The same is shown on my iPad with the latest OS version. 

regards
 Matthias

**Comment by dimsumthinking** [comment]
Thank you - I wonder what’s going on.

Thank you so much for checking

Daniel
