### ISSUE TITLE
Ambiguities in numbering of the book

### ISSUE THREAD

**Issue by ichbindaa** [editorscut/ec008-swift-kickstart-2#99]
Topic: Book Version

> This is version 0.7 for Swift 5, Xcode 10, and iOS 12 released February 7, 2019.

but under Version History:

> Version 0.8
> This is the Swift 5.1 / Xcode 11 release.

I think that the current book version must be 0.8 and should be displayed in that way under "Book version” too.

**Comment by dimsumthinking** [comment]
Thank you. Fixed for next release
